version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db-production/:/var/lib/postgresql/data/
    expose: 
      - "5432"
    networks:
      api_net:
        ipv4_address: 172.16.25.2
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile-production
    depends_on:
      - db
    environment:
      - DB_URL=${DB_URL}
    command: ash -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      api_net:
        ipv4_address: 172.16.25.3
  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile-production
    ports:
      - "8000:8000"
    networks:
      api_net:
        ipv4_address: 172.16.25.4
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile-production
    ports:
      - "80:80"
      - "443:443"
    networks:
      web_net:
        ipv4_address: 172.16.50.2
    



networks:
  api_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.25.0/24
  web_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.50.0/24

