version: '3'
services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./database/table.sql:/docker-entrypoint-initdb.d/init.sql
    expose: 
      - "5432"
    #container_name: db
    networks:
      api_net:
        ipv4_address: 172.16.0.2
  api:
    build: ./api
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      api_net:
        ipv4_address: 172.16.0.3
  web:
    image: "node:19.6.0"
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
    command: bash -c "cd /app && npm install && npm run dev -- --host"
    #container_name: web
    networks:
      web_net:
        ipv4_address: 172.16.1.2
    



networks:
  api_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
  web_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24

