version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose: 
      - "5432"
    networks:
      api_net_test:
        ipv4_address: 172.16.25.2
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/api/
    environment:
      - DB_URL=${DB_URL}
    depends_on: 
      - db
    command: pytest
    networks:
      api_net_test:
        ipv4_address: 172.16.25.3
  web:
    image: "node:19.6.0"
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
    command: bash -c "cd /app && npm install && npm run dev -- --host"
    networks:
      web_net_test:
        ipv4_address: 172.16.50.2
    



networks:
  api_net_test:
    ipam:
      driver: default
      config:
        - subnet: 172.16.25.0/24
  web_net_test:
    ipam:
      driver: default
      config:
        - subnet: 172.16.50.0/24

