from typing import Optional

from models import ValuesInt
from pydantic import BaseModel, constr
from sqlalchemy import select
from sqlalchemy.orm import Session


class ValueInt(BaseModel):
    id: Optional[int]
    value: int
    offer_id: int
    field_id: int

    class Config:
        orm_mode = True

    @classmethod
    async def add(cls, value_int: 'ValueInt', db: Session) -> 'ValueInt':
        """
        Add a value_int to the database.
        The value_int's id is auto generated by the database.
        The id is suppressed without warning.
        """
        values = value_int.dict()
        values.pop('id')
        db_value_int = ValuesInt(**values)
        
        db.add(db_value_int)
        db.commit()
        db.refresh(db_value_int)
        return db_value_int

    @classmethod
    async def get(cls, id: int, db: Session) -> Optional['value_int']:
        """Get a value_int from the database from its id."""
        value_int = db.query(ValuesInt).filter(ValuesInt.id == id).first()
        return value_int
    
    @classmethod
    async def get_by_offer_id(cls, offer_id: int, db: Session) -> Optional['value_int']:
        """Get a value_int from the database from its offer_id."""
        value_int = db.query(ValuesInt).filter(ValuesInt.offer_id == offer_id).all()
        return value_int
    
    @classmethod
    async def get_by_field_id(cls, field_id: int, db: Session) -> Optional['value_int']:
        """Get a value_int from the database from its field_id."""
        value_int = db.query(ValuesInt).filter(ValuesInt.field_id == field_id).all()
        return value_int
    
    @classmethod
    async def get_by_offer_id_and_field_id(cls, offer_id: int, field_id: int, db: Session) -> Optional['value_int']:
        """Get a value_int from the database from its field_id."""
        value_int = db.query(ValuesInt).filter(ValuesInt.offer_id == offer_id, ValuesInt.field_id == field_id).first()
        return value_int

    @classmethod
    async def get_all(cls, db: Session) -> list['value_int']:
        """Return a list of all ValuesInt from the database."""
        return db.query(ValuesInt).all()

    @classmethod
    async def delete(cls, id: int, db: Session) -> Optional['value_int']:
        """Delete a value_int and return it. Return None if the value_int does not exists."""
        value_int = await cls.get(id, db)
        if value_int:
            db.delete(value_int)
            db.commit()
        return value_int
