from typing import Optional

from models import ValuesString
from pydantic import BaseModel, constr
from sqlalchemy import select
from sqlalchemy.orm import Session


class ValueString(BaseModel):
    id: Optional[int]
    value: int
    offer_id: int
    field_id: int

    class Config:
        orm_mode = True

    @classmethod
    async def add(cls, value_string: 'ValueString', db: Session) -> 'ValueString':
        """
        Add a value_string to the database.
        The value_string's id is auto generated by the database.
        The id is suppressed without warning.
        """
        values = value_string.dict()
        values.pop('id')
        db_value_string = ValuesString(**values)
        
        db.add(db_value_string)
        db.commit()
        db.refresh(db_value_string)
        return db_value_string

    @classmethod
    async def get(cls, id: int, db: Session) -> Optional['value_string']:
        """Get a value_string from the database from its id."""
        value_string = db.query(ValuesString).filter(ValuesString.id == id).first()
        return value_string
    
    @classmethod
    async def get_by_offer_id(cls, offer_id: int, db: Session) -> Optional['value_string']:
        """Get a value_string from the database from its offer_id."""
        value_string = db.query(ValuesString).filter(ValuesString.offer_id == offer_id).all()
        return value_string
    
    @classmethod
    async def get_by_field_id(cls, field_id: int, db: Session) -> Optional['value_string']:
        """Get a value_string from the database from its field_id."""
        value_string = db.query(ValuesString).filter(ValuesString.field_id == field_id).all()
        return value_string
    
    @classmethod
    async def get_by_offer_id_and_field_id(cls, offer_id: int, field_id: int, db: Session) -> Optional['value_string']:
        """Get a value_string from the database from its field_id."""
        value_string = db.query(ValuesString).filter(ValuesString.offer_id == offer_id, ValuesString.field_id == field_id).first()
        return value_string

    @classmethod
    async def get_all(cls, db: Session) -> list['value_string']:
        """Return a list of all ValuesString from the database."""
        return db.query(ValuesString).all()

    @classmethod
    async def delete(cls, id: int, db: Session) -> Optional['value_string']:
        """Delete a value_string and return it. Return None if the value_string does not exists."""
        value_string = await cls.get(id, db)
        if value_string:
            db.delete(value_string)
            db.commit()
        return value_string
