from typing import Optional

from models import ValuesBool
from pydantic import BaseModel, constr
from sqlalchemy import select
from sqlalchemy.orm import Session


class ValueBool(BaseModel):
    id: Optional[int]
    value: int
    offer_id: int
    field_id: int

    class Config:
        orm_mode = True

    @classmethod
    async def add(cls, value_bool: 'ValueBool', db: Session) -> 'ValueBool':
        """
        Add a value_bool to the database.
        The value_bool's id is auto generated by the database.
        The id is suppressed without warning.
        """
        values = value_bool.dict()
        values.pop('id')
        db_value_bool = ValuesBool(**values)
        
        db.add(db_value_bool)
        db.commit()
        db.refresh(db_value_bool)
        return db_value_bool

    @classmethod
    async def get(cls, id: int, db: Session) -> Optional['value_bool']:
        """Get a value_bool from the database from its id."""
        value_bool = db.query(ValuesBool).filter(ValuesBool.id == id).first()
        return value_bool
    
    @classmethod
    async def get_by_offer_id(cls, offer_id: int, db: Session) -> Optional['value_bool']:
        """Get a value_bool from the database from its offer_id."""
        value_bool = db.query(ValuesBool).filter(ValuesBool.offer_id == offer_id).all()
        return value_bool
    
    @classmethod
    async def get_by_field_id(cls, field_id: int, db: Session) -> Optional['value_bool']:
        """Get a value_bool from the database from its field_id."""
        value_bool = db.query(ValuesBool).filter(ValuesBool.field_id == field_id).all()
        return value_bool
    
    @classmethod
    async def get_by_offer_id_and_field_id(cls, offer_id: int, field_id: int, db: Session) -> Optional['value_bool']:
        """Get a value_bool from the database from its field_id."""
        value_bool = db.query(ValuesBool).filter(ValuesBool.offer_id == offer_id, ValuesBool.field_id == field_id).first()
        return value_bool

    @classmethod
    async def get_all(cls, db: Session) -> list['value_bool']:
        """Return a list of all ValuesBool from the database."""
        return db.query(ValuesBool).all()

    @classmethod
    async def delete(cls, id: int, db: Session) -> Optional['value_bool']:
        """Delete a value_bool and return it. Return None if the value_bool does not exists."""
        value_bool = await cls.get(id, db)
        if value_bool:
            db.delete(value_bool)
            db.commit()
        return value_bool
