name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the api
      run: ./marketease.py --prod build api
    - name: Build the proxy
      run: ./marketease.py --prod build proxy
    - name: Build the web
      run: ./marketease.py --prod build web
    - name: Run the api
      run: ./marketease.py --prod up api
    - name: Run the proxy
      run: ./marketease.py --prod up proxy
    - name: Run the web
      run: ./marketease.py --prod up web
